### ISSUE TITLE
Removing barcodes from raw signal

### ISSUE THREAD

**Issue by danarte** [jts/nanopolish#1018]
Hi,

I've asked this question in the ONT forum and was directed here, unfortunately I couldn't find the relevant part in the documentation for my question, I hope some users/developers here could help.

I have basecalled (with alignment) fast5 files from a multiplexed sequencing experiment and I want to extract the raw electrical current corresponding only to the actual genomic sequence that was in the original DNA sample.

I know that the raw electrical current contains signal from the barcodes and adaptors as well, so I'm wondering how can I remove this signal which is unwanted in my analysis.

The perfect solution for me would be a simple integer number for every read (fast5 files with multiple reads) that denotes the beginning of the raw signal of the actual DNA molecule (meaning after the barcode and the adapter).
Important to note - not all reads are aligned, but we still want to use the not aligned reads as well, just without the barcode signal as well, meaning looking at this from the perspective of alignment to the genome is not the best solution for us.

I attach an example from a line in the sequencing_summary.txt file and the corresponding read from the fast5 file as outputted by h5dump.

(Probably better viewed by copying it to your text editor )

Summary file:

[https://paste.c-net.org/MailroomStaples](https://paste.c-net.org/MailroomStaples)

FAST5 file output:
[https://paste.c-net.org/AdmitHardcore](https://paste.c-net.org/AdmitHardcore)

**Comment by jts** [comment]
Hi @danarte,

Without using a reference genome this is tricky. The best suggestion I can think of is to use a debug feature of nanopolish that is currently only available on the r10 branch: https://github.com/jts/nanopolish/blob/r10/src/nanopolish_dump_initial_alignment.cpp. This program will write nanopolish's initial signal-to-read alignment to stdout. You could use this to identify the range of samples that correspond to the genomic part of the read (which I assume you can identify from the basecaller or demultiplexer), then extract those samples.

Note that I can't make any claims about the accuracy of this alignment - it is by design a crude first pass that is optimized for speed not accuracy. Maybe the alignment is good enough for your purpose but you should evaluate whether it does what you want.

Jared
