### ISSUE TITLE
no alignment in most of the reads

### ISSUE THREAD

**Issue by Arkadiy-Garber** [jts/nanopolish#1077]
Hi, this is the 7th software I've been trying for methylation calling from ONP data. It has seemed to have gotten closest to finally working and predicting some methylation. However, I am getting the following output:

```
(base) MAB@Axceleron-WKS:~/2748_NP_methylation/fastq_pass/barcode12/assembly$ nanopolish call-methylation --reads /data/MAB/2748_NP_methylation/fast5_pass/single_barcode12.guppy/pass/combined.fastq --bam /data/MAB/2748_NP_methylation/fastq_pass/barcode12/assembly/assembly.sorted.bam --genome /data/MAB/2748_NP_methylation/fastq_pass/barcode12/assembly/assembly.fasta -t 16
chromosome	strand	start	end	read_name	log_lik_ratio	log_lik_methylated	log_lik_unmethylated	num_calling_strands	num_motifs	sequence
[post-run summary] total reads: 83813, unparseable: 0, qc fail: 0, could not calibrate: 3, no alignment: 83810, bad fast5: 0
```

Why are there no alignments? I preceded this command with minimap alignment, as per tutorial.

**Comment by jts** [comment]
This is referring to an internal signal-to-read alignment, not the .bam you provide.This alignment step likely failed because the data you provided is different from what nanopolish expects (dna from r9.4 pore)JaredOn Apr 8, 2023, at 7:47 PM, Arkadiy-Garber ***@***.***> wrote:﻿
Hi, this is the 7th software I've been trying for methylation calling from ONP data. It has seemed to have gotten closest to finally working and predicting some methylation. However, I am getting the following output:
(base) ***@***.***:~/2748_NP_methylation/fastq_pass/barcode12/assembly$ nanopolish call-methylation --reads /data/MAB/2748_NP_methylation/fast5_pass/single_barcode12.guppy/pass/combined.fastq --bam /data/MAB/2748_NP_methylation/fastq_pass/barcode12/assembly/assembly.sorted.bam --genome /data/MAB/2748_NP_methylation/fastq_pass/barcode12/assembly/assembly.fasta -t 16
chromosome	strand	start	end	read_name	log_lik_ratio	log_lik_methylated	log_lik_unmethylated	num_calling_strands	num_motifs	sequence
[post-run summary] total reads: 83813, unparseable: 0, qc fail: 0, could not calibrate: 3, no alignment: 83810, bad fast5: 0

Why are there no alignments? I preceded this command with minimap alignment, as per tutorial.

**Comment by Arkadiy-Garber** [comment]
I have dna from r10.4 pore. Is nanopolish not compatible with that?

**Comment by jts** [comment]
Correct, see here: https://github.com/jts/nanopolish#a-note-on-r10-supportOn Apr 8, 2023, at 8:36 PM, Arkadiy-Garber ***@***.***> wrote:﻿
I have dna from r10.4 pore. Is nanopolish not compatible with that?

**Comment by hasindu2008** [comment]
@Arkadiy-Garber you may try f5c, that supports r10 now https://github.com/hasindu2008/f5c.

**Comment by Arkadiy-Garber** [comment]
Thanks, Jared. From that thread, what does "methylation calling is accurate enough to not require signal-level analysis" mean? Is there another way to extract methylation/modification information from the sequencing data?

@hasindu2008, thanks I will give that a try!

**Comment by jts** [comment]
I mean that methylation called by the basecallers (guppy or dorado) is now the state of the art and much easier to run.On Apr 8, 2023, at 9:45 PM, Arkadiy-Garber ***@***.***> wrote:﻿
Thanks, Jared. From that thread, what does "methylation calling is accurate enough to not require signal-level analysis" mean? Is there another way to extract methylation/modification information from the sequencing data?
@hasindu2008, thanks I will give that a try!
