### ISSUE TITLE
Error Installing Nanopolish

### ISSUE THREAD

**Issue by annamack** [jts/nanopolish#1085]
Hello,

I am trying to install Nanopolish on a Linux computing cluster with a GCC compiler. Here is what I ran:

git clone --recursive https://github.com/jts/nanopolish.git
cd nanopolish/
make

Here is the error I am getting:
make: *** [Makefile:162: eigen/INSTALL] Error 4

![Screenshot 2023-05-25 144107](https://github.com/jts/nanopolish/assets/134643359/7fe45fb3-f69e-4a76-b7f3-28319ef42c14)

Any help is appriciated!

**Comment by sbridgett** [comment]
I was also having difficulty installing nano polish, due to an issue with hdf5. 

So instead of compiling nano polish from source, I have installed it using conda as follows:


**(1)** Installed miniconda from:  https://docs.conda.io/en/latest/miniconda.html
Then logout and login again to enable conda.


**(2)** Then set channels:

```
conda config --add channels bioconda

conda config --add channels conda-forge
```

(This 'conda-forge' channel is needed to install correct hdf5 version for Nanopolish 0.14.0, otherwise conda will install the earlier version 0.13.2 of Nanopolish.)
 

**(3)** Updated conda and installed mamba:

```
conda update -n base -c defaults conda

conda install mamba
```

**(4)** Installed Nanopolish 0.14.0:

```
conda create --name nanopolish
conda activate nanopolish

mamba install nanopolish
```

which installed the 0.14.0 version of nanopolish.

**(5)** Then to run 
Will need to activate the env:

  conda activate nanopolish

Or in a script submitted to a compute cluster add:

```
  source $(conda info --base)/etc/profile.d/conda.sh
  conda activate nanopolish
```


I hope that helps.

**Comment by rdeborja** [comment]
@annamack It seems like a server issue with gitlab.com:
```
Resolving gitlab.com (gitlab.com)... failed: Temporary failure in name resolution.
wget: unable to resolve host address gitlab.com
```
I was able to  manually retrieve the file:
```
wget https://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.tar.bz2;
```
I'm hoping it was a rare occurrence.  Could you possibly try installing `nanopolish` again?

Although I personally agree with @sbridgett and use `conda` myself.

**Comment by annamack** [comment]
@rdeborja 
Yes, I was able to install using wget and the link you provided.

Thank you for your assistance!

**Comment by annamack** [comment]
@rdeborja 
Yes, I was able to install using wget and the link you provided.

Thank you for your assistance!
