### ISSUE TITLE
nanopolish eventalign fails on a single duplicate read

### ISSUE THREAD

**Issue by scottgigante** [jts/nanopolish#128]
I am running nanopolish eventalign using the recommended pipeline:
basecall -> ```poretools fasta (--type fwd) ```-> ```bwa mem``` -> ```samtools index``` -> ```nanopolish eventalign```

However, for some reason my fasta file contains duplicate reads. Nanopolish eventalign discovers these and exits:
```Error: duplicate read name cc330940-2bb3-4f60-93cb-cd6134d68061_Basecall_2D_template found in fasta file```

The large majority of the reads in my fasta file are *not* duplicates. Is it possible to simply skip the duplicate read, rather than exiting and giving no output?

Thanks!

**Comment by jts** [comment]
Hi Scott,

I'm not sure I want to allow duplicates. I exit with an error here as a QC step - while a single duplicated read won't change the results much, it usually indicates an upstream problem that should be fixed (like including a set of files twice). I'm happy to discuss but it will take a bit of convincing for me to remove this error check.

Jared

PS: the new recommended pipeline uses `nanopolish extract` rather than `poretools`.

**Comment by scottgigante** [comment]
Hi Jared,

My apologies - I had assumed the error was coming from supplementary alignments, but in fact I did indeed have duplicated files hiding in a subdirectory found by my call to ```poretools``` using ```find``` and ```parallel```.

Might I suggest that, upon exiting, ```nanopolish``` print the directories of the fast5 files in question? This would make the error message much more informative.

Thanks for your help, and thank you also for the note on the pipeline - I will have a look at ```nanopolish extract```.

Scott
