### ISSUE TITLE
Methylation

### ISSUE THREAD

**Issue by rojinsafavi** [jts/nanopolish#157]
Hello,

I have a set of methylated data with a known modified motif. I was wondering how I can use call_methylation or methyltrain to train a model (an HMM I guess?)  to detect this specific motif as methylated motif and use this trained model on my test data to measure the accuracy. 

Thanks!

**Comment by jts** [comment]
Hi,

Training a methylation model is a little involved. First, you need to define an alphabet that describes to nanopolish what the methylation motif looks like, and how to reverse-complement it. Have a look in https://github.com/jts/nanopolish/blob/master/src/common/nanopolish_alphabet.h and https://github.com/jts/nanopolish/blob/master/src/common/nanopolish_alphabet.cpp for examples of the CpG motif.

You then need to align your reads to the reference genome and make a version of the reference where the methylated bases are replaced by `M` symbols. Finally, you have to tell methyltrain which alphabet to use:

https://github.com/jts/nanopolish/blob/master/src/nanopolish_methyltrain.cpp#L887

I probably forgot a step or two but this should at least give you a start. This is something we should probably write a tutorial for since I've had this question a few times. Let me know how it goes and I can help further.

Jared

**Comment by rojinsafavi** [comment]
Hello Jared,
Thanks for your quick response. Writing a tutorial would be great :)

I noticed that the motif that I'm interested in is already implemented (CCTGG). So I guess I do not need to make any change to the first two links you sent.
Should I make a version of the reference genome with the corresponding methylated bases and then align reads to this modified reference genome? And do you suggest using eventalign? 

Thanks,
Rojin

**Comment by rojinsafavi** [comment]
I'm not very familiar with C++ language.
I'm getting this error when I use your R9 models:
Here are my steps:

1) replaced methylated base with M in reference sequence, named it methylated.fasta
2) bwa index methylated.fasta
3) extracted reads:
nanopolish extract -r --type template fast5_folder > reads.fa
4)bwa mem -x ont2d -t 8 methylated.fasta reads.fa | samtools sort -o reads.sorted.bam -T reads.tmp -
5) samtools index reads.sorted.bam
6)nanopolish methyltrain --reads reads.fa --bam reads.sorted.bam --genome methylated.fasta -m /etc/r9-models/r9.4_450bps.nucleotide.5mer.template.model

and I get this error:
Error: unknown model:

Also, should I pass the motif using --train-kmers= CCTGG ?

Thank you very much!

**Comment by jts** [comment]
Can you try without giving the models file (omit the `-m` parameter)? You'll have to recompile the code to change the `mtrain_alphabet` variable though.

**Comment by rojinsafavi** [comment]
For now I am using "CG" motfi to get an understanding of how the training works, so I did not make any change to the code

so I removed the -m flag and now it gives me this error:

(env) -bash-4.2$ nanopolish methyltrain --reads reads.fa --bam reads.sorted.bam --genome replaced.fasta

nanopolish: src/nanopolish_methyltrain.cpp:879: int methyltrain_main(int, char**): Assertion `!opt::models_fofn.empty()' failed.
Aborted (core dumped)

**Comment by jts** [comment]
Hi,

I'm travelling right now but I don't want to leave you without a response. I suggest you have a look at the full training pipeline we used for our paper:

https://github.com/jts/methylation-analysis/blob/master/pipeline.make#L282

You'll have to modify it a bit but it should show you how to set up the models, reference and input data to run methyltrain.

Let me know how it goes.

jared

**Comment by jts** [comment]
Hi @rojinsafavi,

If you have any other problems with methylation training (either here or in the other issue where you asked about 5-mers) could you let me know?

Jared
