### ISSUE TITLE
Recommendations for very high coverage

### ISSUE THREAD

**Issue by zachcp** [jts/nanopolish#228]
Hi @jts ,

I'm wondering if you have any suggestions for very-high coverage datasets (~1000x). Would you recommend changing the defaults (mincoverage, min-fraction-error) or do you think a random subset of the data is a better option. If the latter, would you have any suggestions on the ideal coverage for nanopolish?

Thanks,
zach cp

**Comment by jts** [comment]
Are you calling SNPs or polishing an assembled genome?

**Comment by zachcp** [comment]
Polishing an assembled genome.

**Comment by jts** [comment]
I suggest downsampling to about 100-200x then.

**Comment by zachcp** [comment]
ok. thanks

**Comment by gwaldbieser** [comment]
What if we want to downsample the fastq for quality and read length instead of bulk coverage? 

Nanopolish (v0.10.2) index runs to completion when I include all fast5 files, the a file of summary file names, and a concatenated file of fastqs:

```
#!/bin/bash
/home/software/nanopolish/nanopolish index      \
        -d /home/Microbial/kidney/reads/0   \
        -d /home/Microbial/kidney/reads/1   \
        -d /home/Microbial/kidney/reads/10   \
        -d /home/Microbial/kidney/reads/100  \
         ...
         ...
        -d /home/Microbial/kidney/reads/98  \
        -d /home/Microbial/kidney/reads/99  \
        -f /home/Microbial/kidney.SeqFileList_1  Kidney1.all.fastq 1>polish.log 2>&1

```
However, when I replace the all.fastq file to contain only reads at q10 and 5000bp minimum length, Nanopolish goes through all the fast5 directories but reports that no fast5 files were found. 

$cat polish.log
[readdb] indexing /home/geoff/Microbial/Sleepy/Sleepy1kidney/reads/0
[readdb] indexing /home/geoff/Microbial/Sleepy/Sleepy1kidney/reads/1
[readdb] indexing /home/geoff/Microbial/Sleepy/Sleepy1kidney/reads/10
[readdb] indexing /home/geoff/Microbial/Sleepy/Sleepy1kidney/reads/100
...
...
[readdb] indexing /home/geoff/Microbial/Sleepy/Sleepy1kidney/reads/98
[readdb] indexing /home/geoff/Microbial/Sleepy/Sleepy1kidney/reads/99
Error: no fast5 files found

Can this be done?
