### ISSUE TITLE
Allow multiple fastq files from the same sample to be used in a single nanopolish run

### ISSUE THREAD

**Issue by gringer** [jts/nanopolish#245]
I've got multiple sequencing runs from the same source that I'd like to use with nanopolish (in separate directories). It'd be useful if I could specify these runs separately in the nanopolish command line(s), instead of having to combine them all. I understand the workaround is not too taxing, it just needs a bit of extra sequence duplication and directory shifting:

    pv ../called_albacore_2.0.2_?_1*/workspace/pass/fastq_all.fastq.fa.gz | zcat | perl -pe 'tr/$//d' | gzip > ./fastq_called_albacore_2.0.2_all_passed.fa.gz
    ~/install/nanopolish/nanopolish index -v -d all_run_FAST5 fastq_called_albacore_2.0.2_all_passed.fa.gz

**Comment by jts** [comment]
Note you can now (since late last week) give the `-d` argument to `index` multiple times to avoid moving fast5s around (or creating symlinks) but you still need to make one input fasta/fastq. I'll keep this request in mind but it won't happen soon since it would be a rather big change to how nanopolish handles I/O.

**Comment by colindaven** [comment]
Good to know, this was exactly the question I was about to pose. Thanks
