### ISSUE TITLE
Clarifications on the nanopolish variants VCF 

### ISSUE THREAD

**Issue by Chjulian** [jts/nanopolish#263]
Hi everyone,

I am calling variants from viral amplicons in order to identify intra-host variants.

I am using nanopolish 0.8.3, but I modified the code so it groups all variants that are within 3 bp of each other. I also increased the max haplotypes to avoid the 'Number of variants in span (22)' warning (I have tried up to 1000000, and nanopolish is so far handling it). 

`nanopolish variants --threads 8 --reads barcode01.fastq.gz --bam barcode01.sorted.bam --genome ref.fasta --outfile barcode01.eventalign.vcf --ploidy 1  --calculate-all-support
`

However, I need some help concerning the interpretation of the nanopolish VCF before proceeding with the analysis. I hope someone can shed light on. 

1.	Concerning QUAL, when I call genome variants with bcftools/samtools I usually keep variants over 20 or 30 (to be more stringent). With nanopolish I usually get QUAL values in the other of thousands. Are the values in the other of thousands not necessarily very informative and thus should I stick to my filtering setting?

```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample
ref	432	.	G	A	2802.8	PASS	BaseCalledReadsWithVariant=150;BaseCalledFraction=0.441176;TotalReads=335;AlleleCount=1;SupportFraction=0.575034;SupportFractionByBase=0.759,0.022,0.193,0.026	GT	1
ref	440	.	CA	C	42.8	PASS	BaseCalledReadsWithVariant=142;BaseCalledFraction=0.417647;TotalReads=335;AlleleCount=1;SupportFraction=0.477969;SupportFractionByBase=0.096,0.818,0.028,0.058	GT	1
ref	475	.	G	A	3390.2	PASS	BaseCalledReadsWithVariant=329;BaseCalledFraction=0.967647;TotalReads=336;AlleleCount=1;SupportFraction=0.98979;SupportFractionByBase=0.953,0.021,0.007,0.020	GT	1

```
2.	I was expecting that ‘SupportFraction’ and the respective ‘SupportFractionByBase’ were somewhat similar, but this is not always the case. Are those instances where they are quite different a cause for concern or is ‘SupportFraction’ calculated differently? 

```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample
ref	426	.	G	A	2802.8	PASS	BaseCalledReadsWithVariant=167;BaseCalledFraction=0.491176;TotalReads=335;AlleleCount=1;SupportFraction=0.602026;SupportFractionByBase=0.913,0.013,0.062,0.012	GT	1
```

3.	To my understanding, nanopolish (variants calling mode) uses basecalled reads data to find candidate SNPs, but QUAL actually comes from probability calculations using the supporting event-space reads, right? Thus, ‘TotalReads’ (The number of event-space reads used to call the variant) should be a parameter guiding the minimum-read-depth filtering? Is there a rule of thumb for this purpose?

```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample
ref	297	.	C	T	48.1	PASS	BaseCalledReadsWithVariant=233;BaseCalledFraction=0.712538;TotalReads=9;AlleleCount=1;SupportFraction=0.819988;SupportFractionByBase=0.100,0.136,0.028,0.736	GT	1
ref	320	.	C	T	2048.7	PASS	BaseCalledReadsWithVariant=303;BaseCalledFraction=0.90991;TotalReads=294;AlleleCount=1;SupportFraction=0.859048;SupportFractionByBase=0.029,0.090,0.008,0.872	GT	1
```

4.	How do I interpret ‘SupportFractionByBase’ for deletions and insertions? I am reading ‘SupportFractionByBase’ as ACGT, but I don’t see any suppor for ‘C’ in position 661 below

```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample
ref	661	.	G	GC	3985.6	PASS	BaseCalledReadsWithVariant=220;BaseCalledFraction=0.654762;TotalReads=333;AlleleCount=1;SupportFraction=0.902106;SupportFractionByBase=0.317,0.031,0.584,0.068	GT	1
ref	664	.	GA	G	3985.6	PASS	BaseCalledReadsWithVariant=132;BaseCalledFraction=0.392857;TotalReads=333;AlleleCount=1;SupportFraction=0.444635;SupportFractionByBase=0.234,0.024,0.715,0.026	GT	1
```

Cheers!

Ch. Julian

**Comment by jts** [comment]
Hi @Chjulian,

Great questions, here are answers:

1. the QUAL values reported by nanopolish are not well calibrated so you will have to use different thresholds than when calling with samtools on Illumina data. We've found it is best to filter based on SupportFraction rather than QUAL (@nickloman any comments?)

2. SupportFraction is the fraction of reads that support the variant haplotype out of all the haplotypes tested. In the case where many possible variants are tested (for instance near indels with nearby SNPs) SupportFraction may be low. I am considering changing SupportFraction to be the fraction of reads that support the variant haplotype better than the reference haplotype. This may be a somewhat more intuitive measure than the current SupportFraction, which considers haplotypes that are not visible to the user.

3. Yes, `TotalReads` should be used for depth-based filtering. As you have high-depth amplicons you can set a relatively high depth (>100x?). I would be suspicious of calls with fewer than 20 or 30 `TotalReads` in general.

4. I should not output SupportFractionByBase for indels, good catch. I will remove this.

I hope this helps,
Jared

**Comment by Chjulian** [comment]
@jts great feedback!
