### ISSUE TITLE
nanopolish call-methylation core dumped error

### ISSUE THREAD

**Issue by PengNi** [jts/nanopolish#289]
Hi, I'm running Nanopolish call-methylation. But I got an error:
```
nanopolish: src/nanopolish_squiggle_read.cpp:1015: void SquiggleRead::build_event_map_2d_r7(): Assertion `erfb.indices[si].start < events[si].size()' failed.
./mods_nanopolish.sh: line 26: 17521 Aborted                 (core dumped) nanopolish call-methylation -t $nthread -r $reads_fastq -g $ref_fasta -b $reads_sorted_bam > $methylation_tsv
```
the data I used is ecoli_er2925.native.timp.102615.fast5.tar.gz in PRJEB13021.

**Comment by jts** [comment]
Hi @PengNi,

This error is because the file `ecoli_er2925.native.timp.102615.fast5.tar.gz` contains very old nanopore data that is not supported by the current version of nanopolish. You would have to use an older version to run with this data. Instead I suggest you follow the tutorial we just posted today:

http://nanopolish.readthedocs.io/en/latest/quickstart_call_methylation.html

It uses the latest version of nanopolish on very recent data. Let me know if it helps.

Jared

**Comment by PengNi** [comment]
Thank you Jared.
I tried _nanopolish call-methylation_ on a newer data and it worked!
Gonna close the issue.

Peng
