### ISSUE TITLE
eventalign always returns the same strand

### ISSUE THREAD

**Issue by dbobr** [jts/nanopolish#351]
I have been using various features of nanopolish and have to say, it is quite a powerful and useful tool. Thank you. I have a question regarding output from eventalign.

When using eventalign I only get 't' in the strand column for all of my events. Should this be the case?

In half of my events I can see that the reference_kmer and the model_kmer are the same and the reference position increases as event_index increases. Meaning the read was generated in the same direction as the reference genome I align to.

In the other half of the events from eventalign I see that the position in the reference increases as the event_index decreases. In these events, the reference_kmer is the reverse complement of the model_kmer. Meaning these events come from reads that are from the opposite direction as the reference genome.

However, in both cases the strand is noted as 't'. Is this what the strand column is supposed to indicate or am I mistaken? Is there any other info in the eventalign output that would help me figure out from which side the read came from besides comparing whether or not the event_index is decreasing as the reference position is increasing (i.e. something that would be faster)?

Any help appreciated, thank you!

**Comment by jts** [comment]
Hi @dbobr,

In early ONT data both strands were sequenced for "2D" reads. The first strand was called the template (denoted `t`) and the second strand was called the complement (denoted `c`). Modern ONT data only sequences one strand so you will only see template output. It does not indicate the reference strand, you have to infer this from either the event indices or comparing the model kmer to the ref kmer, as you've found out.

The reason I chose this representation rather than denoting the reference strand is because it was complicated for 2D reads (you could have template-forward, template-reverse, complement-forward, complement-reverse) so I thought it was easier to directly indicate the model kmer used. Now that 2D data isn't used anymore a simpler representation is possible but it is probably too late to change.

Jared

**Comment by dbobr** [comment]
Thanks for the clarification!

**Comment by senyou-hou** [comment]
> Sorry to bother you.
 I found that our data is exactly the same as what you described, so I would like to ask if the current value of the same position can be used as a positive and negative sample? Such as position 14404, referennce_kmer TTCTGC  -->   GCAGAA  in model_kmer, can I represent 86.23 as a value of TTCTGC ? 
 Thank you ver much !
![image](https://user-images.githubusercontent.com/83775254/179404324-82969332-7996-4452-bcfb-2e8a0baa8be4.png)
