### ISSUE TITLE
nanopolish variants calling single nucleotide deletion even though --snps

### ISSUE THREAD

**Issue by francoiskroll** [jts/nanopolish#404]
I hope this is not an error/misunderstanding from my part.

I am running `nanopolish variants` with `--snps` which I can apparently use to **only** call SNPs. My command looks like:

`nanopolish variants --snps -r reads.fastq -b sort.bam -g hg19.fasta -w "chr20:4000000:5000000" -p 2 -o variants_snps.vcf -t 8 --calculate-all-support`

However, nanopolish is still calling two single nucleotide deletions in the `.vcf` output file:

```
[...]
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  sample
chr20   4680251 .       A       G       3210.9  PASS    BaseCalledReadsWithVariant=309;BaseCalledFraction=0.362676;TotalReads=829;AlleleCount=1;SupportFraction=0.484085;SupportFractionByBase=0.501,0.013,0.472,0.014  GT      0/1
chr20   4680447 .       AG      A       35.9    PASS    BaseCalledReadsWithVariant=332;BaseCalledFraction=0.383815;TotalReads=832;AlleleCount=1;SupportFraction=0.455256;SupportFractionByBase=0.779,0.022,0.170,0.029  GT      0/1
chr20   4680485 .       GA      G       639.9   PASS    BaseCalledReadsWithVariant=177;BaseCalledFraction=0.204388;TotalReads=838;AlleleCount=1;SupportFraction=0.471225;SupportFractionByBase=0.196,0.007,0.791,0.005  GT      0/1
chr20   4680642 .       G       A       2329.6  PASS    BaseCalledReadsWithVariant=229;BaseCalledFraction=0.269095;TotalReads=824;AlleleCount=1;SupportFraction=0.682093;SupportFractionByBase=0.622,0.059,0.306,0.014  GT      0/1
```

The second and third variants are single nucleotide deletions (reference AG > alternative A), not single nucleotide polymorphism, correct? Or do you define a SNP as including single nucleotide deletion?

Many thanks!

**Comment by jts** [comment]
The `--snps` option has been disabled for awhile. I will fix it, sorry for the inconvenience.

Jared

**Comment by francoiskroll** [comment]
No worry. Thanks for looking into it!

**Comment by lkhilton** [comment]
I'm trying to polish a portion of the human genome using ONT reads from BAC clones. I'd like to exclude indels and only consider variants that occur in a high proportion of reads, since the source is clonal. I'm finding, however, that neither the --snps tag, nor -m 0.8, is having any effect at all on variants called with nanopolish variants. I'm still getting indels and variants with read support <0.8 (see example output below). 

What's the latest on the return of the --snps feature? Is -m similarly disabled?  

'''
##fileformat=VCFv4.2
##nanopolish_window=1:161500000-162000200
##INFO=<ID=TotalReads,Number=1,Type=Integer,Description="The number of event-space reads used to call the variant">
##INFO=<ID=SupportFraction,Number=1,Type=Float,Description="The fraction of event-space reads that support the variant">
##INFO=<ID=BaseCalledReadsWithVariant,Number=1,Type=Integer,Description="The number of base-space reads that support the variant">
##INFO=<ID=BaseCalledFraction,Number=1,Type=Float,Description="The fraction of base-space reads that support the variant">
##INFO=<ID=AlleleCount,Number=1,Type=Integer,Description="The inferred number of copies of the allele">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  sample
1       161505593       .       T       C       634.7   PASS    TotalReads=72;AlleleCount=1;SupportFraction=0.8744      GT      1
1       161505600       .       T       C       634.7   PASS    TotalReads=72;AlleleCount=1;SupportFraction=0.803634    GT      1
1       161507028       .       TG      T       38.8    PASS    TotalReads=138;AlleleCount=1;SupportFraction=0.532283   GT      1
1       161507243       .       G       A       1061.0  PASS    TotalReads=140;AlleleCount=1;SupportFraction=0.855838   GT      1
1       161507444       .       CT      C       593.5   PASS    TotalReads=143;AlleleCount=1;SupportFraction=0.388466   GT      1
1       161508180       .       T       G       1372.4  PASS    TotalReads=141;AlleleCount=1;SupportFraction=0.910621   GT      1
1       161508925       .       CT      C       83.9    PASS    TotalReads=141;AlleleCount=1;SupportFraction=0.363479   GT      1
'''

**Comment by jts** [comment]
Sorry, I haven't gotten around to re-enable `--snps`. Indels are easy to filter out though after calling.

`-m` is not a filter on `SupportFraction`, it determines how often a variant must be seen in the basecalled reads to be considered a 'candidate' for calling.

Jared

**Comment by jts** [comment]
`--snps` is now re-enabled in c346468
