### ISSUE TITLE
Index problems, variants problems

### ISSUE THREAD

**Issue by OnlyHigh** [jts/nanopolish#406]
Hi, 
Trying to index the reads for processing my data with Nanopolish 
I get the following error:
```
~/nanopolish/nanopolish index -d Default/ default_all.fastq
Error: duplicate read name 35b02ea8-68b0-480d-aa76-209bc8ee7a3d found in fasta file
```

Then trying to run ```nanopolish variants```, I get the following errors with that command lines:
```
~/nanopolish/nanopolish variants --consensus polished.fa -r ../../default_all.fastq -b canu2_graphmap.sorted.bam -g ../../canu2.fasta
Error: genome has multiple contigs, please use -w to specify input region 
```
If I specify anything I get this error:

```
~/nanopolish/nanopolish variants --consensus polished.fa -r ../../default_all.fastq -w 1 -b canu2_graphmap.sorted.bam -g ../../canu2.fasta
error: faidx could not get contig length for contig 1
```
What does this mean?
Can anybody help me, 
Thanks in advance, 
Luis Alfonso.

**Comment by jts** [comment]
Hi,

The first problem is caused by multiple reads having the same name (`35b02ea8-68b0-480d-aa76-209bc8ee7a3d`) in your input file `default_all.fastq`. You will have to fix this before proceeding.

The second problem is that the `-w` parameter expects a string like `contig1:10,000-20,000`. See here for a tutorial:

http://nanopolish.readthedocs.io/en/latest/quickstart_consensus.html

I hope this helps,
Jared

**Comment by OnlyHigh** [comment]
Hi, 
For some reason Albacore, has duplicated some of the reads, in the pass folder... 

Anyway for the ``` -w ``` can I just ask Nanopolish to scan everything in search for methilation, or it has to be step by step?  

Thanks

**Comment by jts** [comment]
You have to use `-w` to scan the genome in regions. For methylation calling you can use relatively large regions (1mb, or even 10mb).

Jared

**Comment by OnlyHigh** [comment]
Thanks, it worked!
