### ISSUE TITLE
Update Conda package?

### ISSUE THREAD

**Issue by lkhilton** [jts/nanopolish#433]
I've been running nanopolish 0.9.0 installed from a Conda package. I'm trying to upgrade to 0.10.0 and running into all kinds of issues. It would be much simpler if the Conda package was updated with 0.10.0. Is that doable?

**Comment by jts** [comment]
@nickloman can you update?

**Comment by lkhilton** [comment]
Do you have a link? I'm not finding it. 

```$ conda search nanopolish
Loading channels: done
# Name                  Version           Build  Channel
nanopolish                0.4.0               0  bioconda
nanopolish            0.6.0.dev    ncurses5.9_0  bioconda
nanopolish                0.6.0    ncurses5.9_0  bioconda
nanopolish                0.7.0    ncurses5.9_0  bioconda
nanopolish                0.7.1    ncurses5.9_0  bioconda
nanopolish                0.7.1    ncurses5.9_1  bioconda
nanopolish                0.7.1    ncurses5.9_3  bioconda
nanopolish                0.8.1    ncurses5.9_3  bioconda
nanopolish                0.8.5    ncurses5.9_3  bioconda
nanopolish                0.8.5    ncurses5.9_4  bioconda
nanopolish                0.9.0    ncurses5.9_0  bioconda
nanopolish                0.9.0 py27_ncurses5.9_1  bioconda
nanopolish                0.9.0 py27_ncurses5.9_2  bioconda
nanopolish                0.9.0 py35_ncurses5.9_1  bioconda
nanopolish                0.9.0 py35_ncurses5.9_2  bioconda
nanopolish                0.9.0 py36_ncurses5.9_1  bioconda
nanopolish                0.9.0 py36_ncurses5.9_2  bioconda
nanopolish                0.9.2      h8d55ff6_5  bioconda
nanopolish                0.9.2    ncurses5.9_0  bioconda
nanopolish                0.9.2 py27_ncurses5.9_4  bioconda
nanopolish                0.9.2 py35_ncurses5.9_4  bioconda
nanopolish                0.9.2 py36_ncurses5.9_4  bioconda```

**Comment by jts** [comment]
https://github.com/bioconda/bioconda-recipes/pull/10333

**Comment by mmiladi** [comment]
As I checked now, the nanopolish has been blacklisted due to clang compilation errors after bioconda recent upgrades, likely for the macOS binaries. So the PR has been ineffective. https://anaconda.org/bioconda/nanopolish/files

@lkhilton What is your host os?
I'll start checking if Linux builds can pass, so we can skip only macOS builds for the moment.

**Comment by mmiladi** [comment]
Linux build passed the CI-test and WIP to try building OSX binary with clang.

**Comment by jts** [comment]
Thanks for looking into this @mmiladi! Let me know if there is anything I can do to help.

**Comment by lkhilton** [comment]
I'm operating on Linux. Thanks for updating me on this!

**Comment by mmiladi** [comment]
@lkhilton  sure! v0.10.1 is now available https://anaconda.org/bioconda/nanopolish/files
@jts Since bioconda in a standard scenario uses clang for OSX, there were issues with integration. Now the conda recipe again uses gcc. 
I guess nanopolish does not support clang. Nevertheless, if interested,  here is the latest clang build error state before switching to gcc: 
`src/pore_model/nanopolish_poremodel.cpp:13:10: fatal error: 'bits/stl_algo.h' file not found` from https://circleci.com/gh/bioconda/bioconda-recipes/21982?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by jts** [comment]
Correct, clang is not supported right now. Thanks for looking into this, and sorry for the slow response, I was away from Toronto.

Jared
