### ISSUE TITLE
polya - segmentation output

### ISSUE THREAD

**Issue by smaegol** [jts/nanopolish#470]
Is it possible to include segmentation output (present in the previous version of the polya_merged branch) in the production version of nanopolish polya? I found it useful for some cases and don't see the point of removing it. Thanks.

**Comment by paultsw** [comment]
Hi smaegol,

The segmentation details are now included by default in the output of the polya subprogram, since we found that the `--segmentation` output mode had much of the same information as the default output (plus 2 extra columns). We decided to just add those two missing columns to the default output instead of supporting two output modes.

The current default output contains the following columns:
* `readname`: the read id (from the fast5 file);
* `contig` & `position`: the aligned reference contig and 5' starting position of the alignment;
* `leader_start`, `adapter_start`, `polya_start`, `transcript_start`: the starting sample indices of the respective regions in a segmentation of the array of raw sequencing samples for the read (note that due to the adapter being bound to the 3' p(A) tail, the array of samples is oriented in the 3'->5' direction).
* `read_rate`: a proxy estimate for the uniform rate at which the sequenced molecule moves thru the pore, measured in #nts/sec (use this with caution; as of right now, this is not tuned to be a definitive value but serves internal purposes);
* `polya_length`: our estimate (in #nts); this is a float rather than integer because of our model;
* `qc_tag`: a tag indicating whether we detected an error in the estimate; generally, only rows marked as `PASS` in this column should be used, but other rows may have (e.g.) diagnostic/debugging value.

The starting sample indices offer a segmentation of the raw squiggle for the read.

Hope that helps; let me know if there's anything else I can clarify.

**Comment by smaegol** [comment]
Thanks, I did not notice that.

**Comment by smaegol** [comment]
I have additional question. I can see that compared to the version which was previously available in polya_merged branch current nanopolish polya produces output with (on average) longer polyA predictions (checked on several datasets, running both previous and current version). 

What can be cause of that? Do you have any calibration sequences withe predefined polyA length you use to check predictions?

**Comment by jts** [comment]
Previously in the `polya-merged` branch we were underestimating the length of longer poly-A tails. We have fixed this in the current version. I've attached results for control sequences with 10nt-100nt tails.
![polya_controls_density](https://user-images.githubusercontent.com/389535/46145760-23857380-c22f-11e8-83d8-6562a3993d82.png)
