### ISSUE TITLE
raw signal correspondent to polyA

### ISSUE THREAD

**Issue by Huanle** [jts/nanopolish#482]
@paultsw 
Hi Paul,
to extract the raw signal of polyA and adapter, do i need to flip the squiggle from fast5/Raw/Reads/Read_#/Signal and then using the starting indices?

Thanks.

Huanlee

**Comment by paultsw** [comment]
Hi Huanle,

The signal array in the fast5 file is shifted and digitized to be an array of integers; the parameters that are required to decode the integer array back to floating point values are in `fast5/UniqueGlobalKey/channel_id`, as the attributes `offset`, `digitisation`, and `range`. You need to shift by the offset and scale multiplicatively to get the floating point pico-ampere values back. (The conversion into an integer format is done so that space is saved.)

You don't need to flip orientation when you use the segmentation values in the polya output TSV file --- those values are in `3'->5'` direction, which is the same direction in which sequencing happens for the direct RNA protocol (this is explained in [the paper introducing nanopore direct RNA sequencing](https://www.nature.com/articles/nmeth.4577)).

Hope that helps!

Cheers,

Paul

**Comment by paultsw** [comment]
They should be 0-indexed/0-based.

**Comment by Huanle** [comment]
thanks Paul. :)

**Comment by jts** [comment]
I'll close this for now, let us know if you have more questions.
