### ISSUE TITLE
Nanopolish variants: proximate variant calls have identical QUAL scores

### ISSUE THREAD

**Issue by IraDeveson** [jts/nanopolish#488]
I am using nanopolish to call variants against a reference genome sequence. Because I am looking for HOM and HET variants, I am running nanopolish with --ploidy=2, rather than using the --consensus option. The tool ran smoothly and has done a decent job of identifying SNVs and indels in my data. However, I have noticed something unexpected in the results: variant calls produced by nanopolish that are close together frequently have identical QUAL scores. For instance, the two SNV calls in the following screenshot have identical QUAL scores (QUAL=1204.3), even though (to my eye, at least), one candidate looks much stronger than the other:

![screen shot 2018-10-18 at 11 07 43 am](https://user-images.githubusercontent.com/29443567/47124096-c037b000-d2c7-11e8-9dbd-aba2a9a41e31.png)

This occurs frequently throughout my output dataset, as you can see in this snapshot of my nanopolish output VCF, where adjacent variants commonly have identical QUAL scores:

![screen shot 2018-10-18 at 11 08 17 am](https://user-images.githubusercontent.com/29443567/47124114-e52c2300-d2c7-11e8-8963-71bf93e81fb0.png)

I am just wondering whether this is expected behaviour (something to do with the way nanopolish calls variants) or whether this might be a bug in the program? Clarification would be greatly appreciated.

My exact command was:

cat regions.bed | awk '{print $1":"$2"-"$3}' | \
parallel --results nanopolish_out -P 8 \
nanopolish variants -t 2 \
-r library.fastq \
-b alignments.bam \
-g reference.fa \
--ploidy 2 --min-candidate-frequency 0.1 \
-o nanopolish_candidates.{1}.vcf -w {1}

All the best :)

Ira

**Comment by jts** [comment]
Hi Ira,

This is working as expected. Since the signals nanopore sequencers measure don't have per-base resolution, we have to group nearby sites together when calling variants. When some nearby sites are grouped together they have the same log-likelihood, and hence get the same quality score in the output.

The example you showed in the screenshot probably indicates nanopolish is being overly conservative in this case. If you're interested in hacking around, you can try to reduce this variable, which will break up the variant calls into smaller groups (maybe try a value of 5):

https://github.com/jts/nanopolish/blob/master/src/nanopolish_call_variants.cpp#L127

You'll have to recompile nanopolish (`make`) if you change that value.

Jared

**Comment by IraDeveson** [comment]
Thanks Jared, that makes perfect sense. I'll have a play around with the min_distance_between_variants value.

Greatly appreciated

Ira
