### ISSUE TITLE
Poly(A) segmentation - converting to base space

### ISSUE THREAD

**Issue by NatPRoach** [jts/nanopolish#513]
Hello, I was wondering if theres any way to convert the segmentation output of the polya estimator in to base space (ie nucleotide coordinates). It would be great to be able to identify the nucleotides in the fastq file corresponding to the poly(A) tail. Is there any way to convert from the indices provided in to nucleotide indices?

**Comment by jts** [comment]
Deferring to @paultsw for this one

**Comment by paultsw** [comment]
Hello @NatPRoach, 

That's a bit of a tough question and requires some further exploration. The reason we perform the analysis and estimation in signal space is because the basecaller calls faulty sequences at the signal close to the adapter (i.e. including the poly(A) region).

So there are two difficulties that spring to mind here:
1) there's no guarantee that (e.g.) if you removed all the nucleotides in the basecalled sequence that corresponded to the transcript, the remaining nucleotides would correspond to the poly(A) region (if there are any remaining);
2) there's no guarantee that the number of nucleotides would be correct --- for example, nanopore basecallers tend to have issues with homopolymers (sometimes they emit a single 5mer for a long homopolymer), and the polyadenylated region is one long homopolymer.

It would require a closer exploratory analysis to see whether or not it is possible to re-basecall the polyadenylated region of the signal or otherwise infer high-quality nucleotide-level information about it. We don't have any concrete plans to support this functionality as of this writing, but that's not to say that we don't plan on taking a closer look at this possibility at some point in the future. So the answer is "no", currently we don't support this.

Cheers,

Paul
