### ISSUE TITLE
Nanopolish variants wants "-w" option 

### ISSUE THREAD

**Issue by rothmi12** [jts/nanopolish#587]
I'm trying to polish some genomes of haploid fungi using fast5 files from multiple MinION sequencing runs, so I downloaded the latest version of nanopolish (using v0.11.1). I have found that the `-f` option makes `nanopolish index` WAY faster, so thanks for that.

Now I'm trying to polish the genomes, using this chunk:
`python /path/to/nanopolish_makerange.py \
	assembly2.contigs.fasta | parallel --results nanopolish.results -P 4 \
	nanopolish variants \
	--reads fastq_final2.fastq \
	--bam sorted.bam \
	--genome assembly2.contigs.fasta \
	--consensus \
	--ploidy=1 \
	--outfile polished.{1}.vcf \
	-t 3`

However, I keep getting this error:
`Error: genome has multiple contigs, please use -w to specify input region`

So I'm a bit confused - I want to polish the whole genome, but I'm not sure how to specify the entire region using the `-w` option. I feel like I'm missing something simple, but can't seem to figure it out. Help?

**Comment by jts** [comment]
By design nanopolish polishes the whole genome in 50,000bp segments at a time. This reduces memory usage and allows you to parallelize if you want. You should use the -w option as described in the README here:

https://github.com/jts/nanopolish#computing-a-new-consensus-sequence-for-a-draft-assembly

**Comment by rothmi12** [comment]
Thanks! Seems to be running now with the -w {1} option.
