### ISSUE TITLE
Methylation calling not utilising many threads

### ISSUE THREAD

**Issue by Shians** [jts/nanopolish#616]
Running `call_methylation` on an HPC with 24 threads allocated only shows nanopolish utilising CPU time roughly 3.5 times the walltime. This suggests to me that it's not really utilising multithreading very intensively. Any ideas what the limiting factors are which contribute to this?

**Comment by hasindu2008** [comment]
If you are using the latest Nanopolish version I have an ultra high suspicion that this is due to the limitation of the HDF5 library which serialises any attempted concurrent accesses to fast5 files. (If you are using an older version before v0.10.2 it can be a few other reasons which are no longer present).

While porting methylation calling for CUDA ([f5c](https://github.com/hasindu2008/f5c/)) I had a similar issue where calling methylation for a 60 Gbase Promethion dataset on a 72 thread server with HD RAID took ~70h wall clock time vs 216h CPU time (around 3X as you observed). I developed a prototype file format (tsv that supports asynchronous I/O, which we call slow5) which brought the wall clock time to ~6h  with a CPU time 215h (~36X).

**Comment by jts** [comment]
Yes, I think the file locking introduced in 1.10 is problematic (see discussion [here](https://github.com/jts/nanopolish/issues/595). I intend to downgrade to hdf5-1.8, it would be interesting to see if it helps.

**Comment by hasindu2008** [comment]
@jts I guess this locking in 1.10 that uses _flock_ is not the cause for the problem (locking in 1.10 affects only if a single file is opened for read/write simultaneously as I understand).

The performance issue in HDF is more likely to be due to the  limitation in the  thread safe version which they mention at  https://portal.hdfgroup.org/display/knowledge/Questions+about+thread-safety+and+concurrent+access

```
Users are often surprised to learn that (1) concurrent access to different datasets in a single HDF5 file and (2) concurrent access to different HDF5 files both require a thread-safe version of the HDF5 library. Although each thread in these examples is accessing different data, the HDF5 library modifies global data structures that are independent of a particular HDF5 dataset or HDF5 file. HDF5 relies on a semaphore around the library API calls in the thread-safe version of the library to protect the data structure from corruption by simultaneous manipulation from different threads. Examples of HDF5 library global data structures that must be protected are the freespace manager and open file lists.
```

Further, they also hint that a thread efficient version is not likely in the near future.
```
The HDF Group has a design plan for a more efficient implementation of thread-safety, but currently does not have the resources to implement the plan. If you are interested in supporting this effort, please contact the HDF Helpdesk.
```

**Comment by jts** [comment]
Yes, I agree @hasindu2008. After a quick benchmark, 1.10 does not seem much slower than 1.8, if any. Btw, sorry for not replying to your email yet, I will try soon.

**Comment by Shians** [comment]
Thanks for the insight @jts and @hasindu2008. I think that HDF5 should be sufficiently performant based on the fact that Guppy seems to be able to churn through the data with all cores working. Perhaps there is some strategy around access patterns that can improve the situation?

I do think the fast5 files need work in general though. The multi-fast5 format seems like a slight improvement, but there are still little oddities like the read number being baked into the access path of the Events rather than being an attribute.

If you want to experiment with tsv then I'd recommend having a look at [Apache Arrow](https://arrow.apache.org) which is meant to be a table-oriented on-disk storage format with cross-language support.

**Comment by hasindu2008** [comment]
@Shians  
I have not run guppy myself. I guess that it uses multiprocessing instead of multithreading (I think guppy is not open source, so no way to verify by looking at the code). But I think you can check if it the case by observing the output of 'top' command (not htop).  Even Nanopolish, run with multiprocessing, i.e. call a number of nanopolish instances in parallel with 1 thread per each instance, you will see that all cores are effectively used. I did this observation for nanopolish some time back. That limitation of HDF5 does not apply to multiple processes as stated in their documentation.

BTW Thanks for the recommendation.

**Comment by Shians** [comment]
It appears to be multithreading, but when I look at `top` it maxes out at around 280% utilisation. The cputime reported when I submit batch jobs is exactly the number of threads x walltime though, so I'm misunderstanding something here.

**Comment by jts** [comment]
HDF5's multithreaded implementation uses global locks, so the CPU utilization is poor. If you use multiple processes instead (which do not share state, so don't lock each other out) then the utilization will be higher. We think guppy uses multiple reading processes, instead of multi-threaded HDF5.
