### ISSUE TITLE
Error: no fast5 files found 

### ISSUE THREAD

**Issue by mdrishti** [jts/nanopolish#638]
Hi,

I have performed an extensive search across all relevant threads in the "issues" section for this specific error. I believe that the command that I used was right, but I am still getting the error. Ofcourse, if  I remove the '-s' option, the files do start getting indexed, but it is going to take a lot of time. I have done basecalling using guppy and am using the lastest version of nanopolish. I installed nanopolish in a conda environment.

Could it be that the format of the sequencing summary file is wrong?
[testSeqSummaryFile.txt](https://github.com/jts/nanopolish/files/3477691/testSeqSummaryFile.txt)

**Comment by jts** [comment]
Can you provide the command you ran, and any output it printed?

**Comment by mdrishti** [comment]
Command: 

nanopolish index -v -s ../sequencing_summary_dummy_1.txt -d /path_to_file/fast5_pass/ /path_to_file/reads.fasta
[readdb] indexing 


Output:

/path_to_file/fast5_pass/
Error: no fast5 files found

**Comment by jts** [comment]
what parameters did you use for guppy?

**Comment by mdrishti** [comment]
I am not sure because I did not do it myselves. But the config file said R9.4_450bps. Are there any specific params that you need to know. Meanwhile, I can ask the service providers(those who did the sequencing for me)  about the params.

**Comment by jts** [comment]
My guess is there is a mismatch between the sequencing_summary file and the fast5 files (for example base calling was run on a different set of fast5 files than your provider sent) which is why indexing works without the `-s` option. Maybe confirm with your sequencing provider that the fast5s you were sent are the files produced by the sequencer during the run, and not the fast5s produced by the basecaller if they used the fast5 output option.

Jared
