### ISSUE TITLE
Potential for speeding up nanopolish index on large number of multi-fast5

### ISSUE THREAD

**Issue by Shians** [jts/nanopolish#640]
From what I understand, the `readdb` file is a map from fastq read names to fast5 filenames. From some very rudimentary benchmarking, for a multi-fast5 with 4000 reads, average fragment size 5.5kb, it takes my local server roughly 13 seconds per fast5 file to generate the `readdb` file. For my runs I have 2000+ fast5 files, which amounts to over 7 hours just to create readdb.

It appeared like the information is obtainable using h5ls, which I attempted to run in parallel. From `top` I saw that although the call took over a minute to complete, each process used only <2% CPU. So I bumped the parallelism up and found that additional calls scaled very well, using 256 processes to index 256 files took about the same amount of time as using 16 processes to process 16 files, taking 5 and 3 minutes respectively. Note that the machine I'm on only has 56 cores, so it's probably the OS level process scheduling that's helping out here.

Here's the prototype I have in R, because it's the language where I find spawning multiple processes for a parallel compute to be the most trivial.  With a tiny bit more wrangling and a write-out call I think I can create a `readdb` file in significantly less time.

```r
library(fs)
library(rhdf5)
library(parallel)
library(purrr)
library(stringr)
library(dplyr)
library(tidyr)

fast5_dir <- "fast5_pass"

f5_files <- dir_ls(fast5_dir)
# sample 256 files from the fast5 directory, necessary for timing because
# h5ls caches results for files and repeated calls finish instantly
f5_files <- sample(f5_files, 256)

# use h5ls to query 256 files at a time
x <- mclapply(
    f5_files,
    partial(h5ls, recursive = FALSE),
    mc.cores = 256L # OS begins complaining when I go up to 512 processes
)

# this creates a table with almost the same information as readdb files
# just need to trim the paths and read names
index <- bind_rows(x, .id = "fast5_file")
```

I believe the same effect can be achieved using a large number of asynchronous calls. Though as I understand it, the current architecture is to parse things into a single `ReadDB` object which is serialised, and the object is probably not thread safe so implementation could get tricky. 

Related note, MacOS default terminal only allows 255 files to be open at a time, so this approach will probably fail silently for them.

**Comment by jts** [comment]
Hi @Shians,

Thanks for this investigation. Indexing fast5s is indeed very slow because we have to open each one individually. We provide an option to use the `sequencing_summary.txt` file as a hint (`-s`) which significantly speeds up indexing. Have you benchmarked this option as well?

We don't implement multi-threaded indexing within nanopolish because libhdf5 has a global lock. In the future I am considering a multi-process I/O model (using `fork`) to get around this but it is far off in my plans for now. It would be similar to your R solution but internal to nanopolish. For now if you index without fast5s you can use an externally-generated .readdb file by renaming it to `<prefix>.index.readdb`.

Jared
