### ISSUE TITLE
5mC detection and mismatch due to the nanopore errors

### ISSUE THREAD

**Issue by vahidAK** [jts/nanopolish#702]
Hi @jts 

Do you consider mismatches with the reference during the detection of 5mC in CpG sites? 
As you know, the error rate of the nanopore is high and there may be many cytosines that actually might not be C when compare them to reference. I was wondering that nanopolish examines cytosines through its HMM that are called C from nanopore and also are C in the ref? or not?

Thanks,
Vahid.

**Comment by jts** [comment]
Hi @vahidAK,

The calling algorithm does not use mismatches in its evaluation of whether a particular base is methylated or not. The basecalled sequence is used to determine which part of the reference the underlying signal data belongs to, but otherwise is not considered in the calling algorithm.

Jared
