### ISSUE TITLE
problem with bam generated with nanopolish

### ISSUE THREAD

**Issue by AAMCgenomics** [jts/nanopolish#76]
Dear Jared Thank you so much with your software. 
I have to questions for you. 
1. I am  having some problems with the bam file generate after the pipe posted for nanopolish in github, I am trying to polish an amplicon experiment using the following code: 
nanopolish eventalign -t 4 --sam -r ZIKV2d2_run.fa -b reads.sorted.bam -g zikagenome2.fa --models nanopolish_models.fofn | samtools view -Sb - | samtools sort -o reads.eventalign.sorted.bam

The bam generated in the first step with bwa give no problems and can be visualized in Table ie. but "reads.eventalign.sorted.bam" can not be visualized in Tablet.

2. Also I tried to use "reads.eventalign.sorted.bam" to generate the consensus with nanopolish_makerange.py , but I am getting  another error "mkdir nanopolish.results/1/259364_V: Permission denied at /usr/bin/parallel line 4990" , I have tried all possible options but now I am stuck. 

I am not a tough bioinformatician in fact I am in the beginning of this path, all your help with be useful.

Thank you in advance for your comments.

**Comment by jts** [comment]
Hi,

The bam file produced by eventalign isn't viewable in tablet as it contains events mapped to the reference, not bases. Tablet won't be able to make sense of this so it will fail.

The command you are using will polish a de novo assembly - this is unnecessary since you have a Zika reference genome. What you want to do is use `nanopolish variants` without the `--consensus` option, and pass the Zika reference with the `-g` option. Also, you don't need the parallel step (which is where the error occurs) since the Zika genome is tiny.   Take a look at how the Zibra project is calling SNPs:

https://github.com/zibraproject/zika-pipeline/blob/master/scripts/variants.sh

I hope this helps, let me know if you need more help.

Jared

**Comment by AAMCgenomics** [comment]
Thank you so much Jared, I have other question.

How must be formated the file in the -w  condition of nanopolish variants?

Thank you so much for your help.

**Comment by AAMCgenomics** [comment]
Dear Jared, Thank you so much again for your help, I got with the solution, was a index missing  for the reference genome, with samtools before nanopolish variants.

Thank you so much for your software and guide.

Best regards

**Comment by jts** [comment]
Great, glad to hear it is working.

Jared
