### ISSUE TITLE
Too much bad fast5

### ISSUE THREAD

**Issue by Coracollar** [jts/nanopolish#820]
Hi,
I am calling methylation with nanopolish and one of my samples' output after calling methylation is only 3.6G, out of a 69G fastq (using only pass reads). 

The out of the job was: [post-run summary] total reads: 10315886, unparseable: 0, qc fail: 1457, could not calibrate: 506, no alignment: 12754, bad fast5: 4309496

And the indexing seems fine: 
[readdb] indexing /data/gpfs/projects/punim1048/allbarcoded/CORT/CORT12/barcode06/
[readdb] num reads: 5601511, num reads with path to fast5: 5601511

[coracollar@spartan-login3 fastq_pass]$ ls -lh
total 80G
-rw-r--r-- 1 coracollar punim1048  69G Aug  3 10:10 CORT12.fastq
-rw-r--r-- 1 coracollar punim1048 9.9G Aug  4 05:26 CORT12.fastq.index
-rw-r--r-- 1 coracollar punim1048 317M Aug  4 05:30 CORT12.fastq.index.fai
-rw-r--r-- 1 coracollar punim1048 8.6M Aug  4 05:30 CORT12.fastq.index.gzi
-rw-r--r-- 1 coracollar punim1048 730M Aug  4 10:19 CORT12.fastq.index.readdb
-rw-r--r-- 1 coracollar punim1048  150 Aug  4 10:19 nanopolishindex.out
-rw-r--r-- 1 coracollar punim1048  312 Aug  3 10:14 nanopolishindex.slurm

Any idea what might be happening?

When I called methylation before in other samples (using an older version of nanopolish though) I obtained 83G methylation calls file out of a 102G fasq file with "[post-run summary] total reads: 14143878, unparseable: 0, qc fail: 10190, could not calibrate: 4544, no alignment: 217499, bad fast5: 53033" . Although the sample giving the error has fewer coverage the difference is just too big.

**Comment by jts** [comment]
Hi,

The usual reason for 'bad fast5' reads is that the fast5 is unaccessible (the path is wrong, file permissions are incorrect). Rarely the signal data in the file can be corrupted in some way (unlikely if the reads basecalled). Also reads with length <20bp will be skipped (unlikely). It is hard to diagnose what the case is here - in future versions I'll try to put in more informative messages since this is a common issue.

Jared
