### ISSUE TITLE
Facing an issue with the 'nanopolish eventalign' command

### ISSUE THREAD

**Issue by aim95** [jts/nanopolish#863]
For detecting 6mA modifications, I am currently working on mCaller program (similar to nanopolish) and following the instructions under 'Pipeline for methylation detection from R9 data'. The extracting and aligning commands generated the required files, but the nanopolish eventalign command couldn't be executed.
The following command was given: nanopolish eventalign -t 1 --scale-events -n -r trytry.fastq -b trytry.sorted.bam -g Desktop/Thesis/example/reference.fasta trytry.eventalign.tsv
But the following error occurred:
contig position reference_kmer read_name strand event_index event_level_mean event_stdv event_length model_kmer model_mean model_stdv standardized_level
[bam process] iterating over region: trytry.eventalign.tsv
[E::sam_itr_next] Null iterator

I would be greatly pleased if you could help me out.
Thankyou.

**Comment by jts** [comment]
Hi @aim95,

I think there is a small error in your command which causes nanopolish to parse the .tsv file as a positional argument holding the coordinates to process. Try this instead:

```
nanopolish eventalign -t 1 --scale-events -n -r trytry.fastq -b trytry.sorted.bam -g Desktop/Thesis/example/reference.fasta > trytry.eventalign.tsv
```

Jared

**Comment by aim95** [comment]
Thankyou very much. This command worked.

**Comment by jeffersmith** [comment]
Hello,@jts. I'm using nanopolish eventalign command to detect m6A modifacations, the following command is given:
nanopolish eventalign --reads fastq/pass.fq.gz --bam bamtx/test.bam --genome refer.fa --signal-index --scale-events --summary nanopolish/summary.txt --thread 32 > nanopolish/eventalign.txt
but it rise an error:
[E::sam_itr_next] Null iterator

The condition of mine seems doesn't like this issue and I have no idea about it because it runs in my another data, I have try to find whether there is a blank lines in refer.fa or in fastq, but I found no.appreciate you very much if you can help me out.
Thanks.
