### ISSUE TITLE
r10 branch still functional?

### ISSUE THREAD

**Issue by lmolokin** [jts/nanopolish#877]
Hi,
Wondering if the r10 branch is still the way to use nanopolish for r10.3 data. Just tried installing it with:

```
git clone --recursive -b r10 https://github.com/jts/nanopolish.git
cd nanopolish
make
```

I updated the eigen download path in the Makefile in order for the make command to run. Afterwords, running nanopolish just leads to a segmentation fault.

There doesn't appear to be much talk of nanopolishing r10 data neither on git or within the nanopore community.  I've only recently started looking at r10 consensus sequences but is the sentiment on r10 is that it's sufficiently good enough after racon polishing alone?

Thanks.

**Comment by jts** [comment]
Hi @lmolokin,

In principle its supported by the r10 branch has lagged behind master a little so may be broken. Usually this happens because the metadata in the fast5 files is no longer what nanopolish expects. I will try to fix this but my time is very limited right now. I suggest you use `medaka` for polishing as it gives state-of-the-art accuracy (for both r9.4 and r10).

I hope that helps,
Jared

**Comment by lmolokin** [comment]
Understood. Thanks for the quick reply.

**Comment by jts** [comment]
Could you provide an example read that demonstrates the segfault?

**Comment by lmolokin** [comment]
It actually happens when I run 'nanopolish' without any options or input e.g. to check version.

**Comment by jts** [comment]
Sorry for the slow reply, I've been caught up with other things. Do you get the same issue with the master branch, or only r10? If its unique to the r10 branch could you try to do `make clean` after switching into the branch, then compiling?
