### ISSUE TITLE
Unable to extract sequences

### ISSUE THREAD

**Issue by matiasirazoqui** [jts/nanopolish#96]
Hi! I'm having trouble extracting the sequences with nanopolish. It always gives me a empty output. This the command I used:
`nanopolish extract -q -o ONT.fq ONT/reads/pass` 
I've tried changing the "type" parameter, extracting FASTA instead of FASTQ, using the recursive option and using the stdout, but I always get a empty output. I've also tried extracting the sequences with other tools and continuing with the nanopolish pipeline, but "eventalign" crashes because of a problem with the sequences and asks me to "re extract" them using extract.
Thank you for your help!

**Comment by mateidavid** [comment]
Generally speaking, in order to be usable with `nanopolish`, the `fast5` files must contain certain types of data. Various settings of the ONT software pipelines might cause the `fast5` files not to have all necessary data. To confirm this is indeed the problem, add `--log-level debug` to your `nanopolish extract` command line, and give it a single `fast5` file (rather than a directory). In the resulting log (which is written to stderr), look for a line containing the string `"preferred_groups"`. If there is nothing else listed on that line, that means there was no usable data in that `fast5` file. Unfortunately, there is no easy fix for this, you have to rerun the ONT basecaller on your dataset with the correct settings.

In more details, `nanopolish extract` is looking for basecalled data (fasta/q) that also has associate event-level data. For example, the following `fast5` groups must be available for `nanopolish` to use 2D basecalled data:
```
/Analyses/Basecall_2D_000/BaseCalled_2D/Fastq
/Analyses/Basecall_1D_001/BaseCalled_template/Events
/Analyses/Basecall_1D_001/BaseCalled_complement/Events
```
These are not filesystem paths, but internal indexes used inside `fast5` files. To explore a given file, use, e.g., `h5dump -n file.fast5`.

**Comment by matiasirazoqui** [comment]
Thanks for your answer! I don't have those groups in my fast5 data. It seems I'll have to rerun the basecalling or look for another way to correct my reads. Once again, thanks!

**Comment by mateidavid** [comment]
The `fast5` library (used under the hood by `nanopolish extract`) incorporates the logic of looking for appropriate groups. So, the log message I mentioned first is a better indication that the files are unusable, rather than looking for those specific groups by hand.

The groups I mentioned are only an example, so you might have `fast5` files that are still usable with `nanopolish`, but containing slightly different groups (e.g. `.../Basecall_2D_000/...` and `.../Basecall_1D_000/...`, the combinations vary depending on the ONT pipeline settings).

**Comment by johnomics** [comment]
I just hit this same problem - no event information in my fast5 files. I can see nanopolish needs the event information for polishing, but why does it need it for extracting? It looks like it just uses the `fast5` library to pull out the existing basecalled FASTQ. Would it be possible to skip the check for event information when just using `extract`?

Also, it would be great if `nanopolish extract` would output a warning if it didn't find any valid reads in a folder - ending silently was quite confusing. It even ended silently with `--verbose` switched on, and the `--log-level` option is undocumented.

**Comment by mateidavid** [comment]
I just made a PR that shows a counter at the end of a run with files seen and reads extracted. I also fixed `-v` to increase verbosity.

As for disabling the checks- The whole point of writing `extract` was to have a tool specifically for processing reads meant to be used with `nanopolish`. There are other tools out there that can extract fastq:

- `poretools`

- in the latest `fast5` I added a program `f5dump`

- with raw `h5py`:
```
import h5py
import sys
p = sys.argv[1]
for fn in sys.argv[2:]:
    f = h5py.File(fn)
    if p in f:
        print(f[p][()].strip())
```
Then, `./fqdump /Analyses/Basecall_2D_000/BaseCalled_2D/Fastq *.fast5` to get 2D data.

**Comment by johnomics** [comment]
Thanks, the counter is very useful. I see it makes sense to keep `extract` for `nanopolish` use - it's just such a nice tool that we've drifted into using it even when we're not polishing... But the problem might go away anyway; we were dealing with locally-basecalled reads, which didn't contain event data, but it seems MinKNOW 1.3.24 will write events for each read. Thanks for your help!

**Comment by jts** [comment]
Locally basecalled reads should contain events using the latest MinKNOW (released yesterday) so I think keeping the current behaviour is the right thing to do.

**Comment by DelphIONe** [comment]
I need help...
I have a Basecalling 1D done with MinKNOW during sequencing. I used Albacore 1.0.3 to do the 2D Basecalling. When I use nanopolish extract, I obtain 0 read : 
nanopolish extract -r -q -t 2d -v --log-level debug -o 2d_albacore103_run24.fastq ~/data/run24/albacore103/workspace/3/ct_39_20170313_FNFAF13217_MN16033_sequencing_run_sample_id_86066_ch399_read5433_strand.fast5
set default log level to: 3
= extract.2 nanopolish_extract.cpp:309 parse_extract_options paths: /home/equipe-cthermes/data/run24/albacore103/workspace/3/ct_39_20170313_FNFAF13217_MN16033_sequencing_run_sample_id_86066_ch399_read5433_strand.fast5
= extract.2 nanopolish_extract.cpp:310 parse_extract_options recurse: yes
= extract.2 nanopolish_extract.cpp:311 parse_extract_options read_type: 2d
= extract.2 nanopolish_extract.cpp:188 process_path /home/equipe-cthermes/data/run24/albacore103/workspace/3/ct_39_20170313_FNFAF13217_MN16033_sequencing_run_sample_id_86066_ch399_read5433_strand.fast5
= extract.3 nanopolish_extract.cpp:120 process_file /home/equipe-cthermes/data/run24/albacore103/workspace/3/ct_39_20170313_FNFAF13217_MN16033_sequencing_run_sample_id_86066_ch399_read5433_strand.fast5
= extract.3 nanopolish_extract.cpp:107 get_preferred_basecall_groups preferred_groups: 
= extract.2 nanopolish_extract.cpp:139 process_file file [/home/equipe-cthermes/data/run24/albacore103/workspace/3/ct_39_20170313_FNFAF13217_MN16033_sequencing_run_sample_id_86066_ch399_read5433_strand.fast5]: no basecalling data suitable for nanoplish
[extract] found 1 files, extracted 0 reads

So, I understand, no usable data, but I see in my fast5 files, there are fastq data ! Mateidavid says :
"you have to rerun the ONT basecaller on your dataset with the correct settings". Ok but what are "correct settings" with Albacore for example. My problem comes from local basecaller or Albacore ?

Thanks a lot for any help,

**Comment by mateidavid** [comment]
Are you sure that particular file contains a 2D basecall group? With `-t 2d`, only 2D basecall groups will be considered. If, e.g., Albacore wasn't able to find 2D data in that particular file, then you wouldn't get any data from that file. Can you post the output of:
```
h5ls -r ~/data/run24/albacore103/workspace/3/ct_39_20170313_FNFAF13217_MN16033_sequencing_run_sample_id_86066_ch399_read5433_strand.fast5 | grep Dataset
```

**Comment by jordur** [comment]
Same here:
```
bec2-jcalvete@Bec2-jcalvete:~/Feina_Jordi/Minion/Bjararaca/Bjararaca_3/rawdata$ nanopolish extract -o prova.fasta test_10/ugm07_20170510_FNFAE31754_MN19775_mux_scan_Bjar_1005_85455_ch102_read12_strand.fast5 --log-level debug
set default log level to: 3
= extract.2 nanopolish_extract.cpp:309 parse_extract_options paths: test_10/ugm07_20170510_FNFAE31754_MN19775_mux_scan_Bjar_1005_85455_ch102_read12_strand.fast5
= extract.2 nanopolish_extract.cpp:310 parse_extract_options recurse: no
= extract.2 nanopolish_extract.cpp:311 parse_extract_options read_type: 2d-or-template
= extract.2 nanopolish_extract.cpp:188 process_path test_10/ugm07_20170510_FNFAE31754_MN19775_mux_scan_Bjar_1005_85455_ch102_read12_strand.fast5
= extract.3 nanopolish_extract.cpp:120 process_file test_10/ugm07_20170510_FNFAE31754_MN19775_mux_scan_Bjar_1005_85455_ch102_read12_strand.fast5
= extract.3 nanopolish_extract.cpp:107 get_preferred_basecall_groups preferred_groups: 
= extract.2 nanopolish_extract.cpp:139 process_file file [test_10/ugm07_20170510_FNFAE31754_MN19775_mux_scan_Bjar_1005_85455_ch102_read12_strand.fast5]: no basecalling data suitable for nanoplish
[extract] found 1 files, extracted 0 reads
```
So my question is: why does this error happen? I mean: I tried nanopolish with some archived Ecoli date and I had no problem. Then, with my own samples I found that no suitable data are available. Since we want to obtain some results, I used poretools but now I would like to polish the assembly with nanopolish_makerange.py but (obviously) I got the following error:
```
[fai_load] build FASTA index.
SquiggleRead: basecall group detection failed:
SquiggleRead: file name [pass_allfast5/ugm07_20170510_FNFAE31754_MN19775_sequencing_run_Bjar_1005_93698_ch192_read1068_strand.fast5]
SquiggleRead: read name [channel_192_64b5224f-fff2-4c0f-a20b-f6421410247f_template]
SquiggleRead: basecall group [1D_000]
SquiggleRead: read_type [0]
SquiggleRead: giving up; re-extract reads with 'nanopolish extract'
```
Do you think that the local basecalling with Albacore could be useful now? I mean, once I got the assembly and the bam alignment file?
More information about the sequencing run could be provided if necessary.
Thanks in advance

**Comment by jts** [comment]
I suspect the 2D dataset names from albacore do not use the same convention as the old metrichor caller, which breaks nanopolish. Could someone provide an example fast5 by email?

**Comment by jordur** [comment]
uhmm.. actually we ran a 1D 48h script using Miknow. Attached you will find 10 f
[test_10_nanopolish.zip](https://github.com/jts/nanopolish/files/1004850/test_10_nanopolish.zip)
ast5 example files. I hope this helps.

**Comment by jts** [comment]
Did you basecall with MinKNOW or albacore?

**Comment by jordur** [comment]
Sorry for the confusion: we performed the local basecalling with MinKNOW  i.e. attached fast5 files were obtained with MinKNOW. 
However, since we have to carry out the basecalling again (we obtained a "giving up; re extract sequences with nanopolish extract" ) I was wondering if Albacore could be useful in order to use resulting fast5 files to polish an assembly previously obtained with the fasta files extacted using poretools. I hope this helps to clarify what has been done with data. Again, apologies.

**Comment by jts** [comment]
`extract` now has an option to force it to use albacore basecalls. Could you try the `-b albacore` option?

**Comment by jordur** [comment]
Did you mean this?
```
nanopolish extract -b albacore ugm07_20170510_FNFAE31754_MN19775_mux_scan_Bjar_1005_85455_ch102_read12_strand.fast5 --log-level debug
```
Resulting:
```
set default log level to: 3
= extract.2 nanopolish_extract.cpp:343 parse_extract_options paths: ugm07_20170510_FNFAE31754_MN19775_mux_scan_Bjar_1005_85455_ch102_read12_strand.fast5
= extract.2 nanopolish_extract.cpp:344 parse_extract_options recurse: no
= extract.2 nanopolish_extract.cpp:345 parse_extract_options read_type: 2d-or-template
= extract.2 nanopolish_extract.cpp:346 parse_extract_options basecaller_name: albacore
= extract.2 nanopolish_extract.cpp:347 parse_extract_options basecaller_version: 
= extract.2 nanopolish_extract.cpp:212 process_path ugm07_20170510_FNFAE31754_MN19775_mux_scan_Bjar_1005_85455_ch102_read12_strand.fast5
= extract.3 nanopolish_extract.cpp:144 process_file ugm07_20170510_FNFAE31754_MN19775_mux_scan_Bjar_1005_85455_ch102_read12_strand.fast5
= extract.3 nanopolish_extract.cpp:131 get_preferred_basecall_groups preferred_groups: 
= extract.2 nanopolish_extract.cpp:163 process_file file [ugm07_20170510_FNFAE31754_MN19775_mux_scan_Bjar_1005_85455_ch102_read12_strand.fast5]: no basecalling data suitable for nanoplish
[extract] found 1 files, extracted 0 reads
```
On the other hand it seems that minKNOW does not work better:
```
nanopolish extract -b minknow ugm07_20170510_FNFAE31754_MN19775_mux_scan_Bjar_1005_85455_ch102_read12_strand.fast5 --log-level debug
```
```
set default log level to: 3
= extract.2 nanopolish_extract.cpp:343 parse_extract_options paths: ugm07_20170510_FNFAE31754_MN19775_mux_scan_Bjar_1005_85455_ch102_read12_strand.fast5
= extract.2 nanopolish_extract.cpp:344 parse_extract_options recurse: no
= extract.2 nanopolish_extract.cpp:345 parse_extract_options read_type: 2d-or-template
= extract.2 nanopolish_extract.cpp:346 parse_extract_options basecaller_name: minknow
= extract.2 nanopolish_extract.cpp:347 parse_extract_options basecaller_version: 
= extract.2 nanopolish_extract.cpp:212 process_path ugm07_20170510_FNFAE31754_MN19775_mux_scan_Bjar_1005_85455_ch102_read12_strand.fast5
= extract.3 nanopolish_extract.cpp:144 process_file ugm07_20170510_FNFAE31754_MN19775_mux_scan_Bjar_1005_85455_ch102_read12_strand.fast5
= extract.3 nanopolish_extract.cpp:131 get_preferred_basecall_groups preferred_groups: 
= extract.2 nanopolish_extract.cpp:163 process_file file [ugm07_20170510_FNFAE31754_MN19775_mux_scan_Bjar_1005_85455_ch102_read12_strand.fast5]: no basecalling data suitable for nanoplish
[extract] found 1 files, extracted 0 reads
```
As mentioned above, since "get_preferred_basecall_groups preferred_groups" seems to be blank, the basecalling should be carried out again, shouldn't it? 
Sorry for the inconvenience

**Comment by jts** [comment]
Yes, that's what I meant. I'll take a look at your data and get back to you.

**Comment by jts** [comment]
Ok, I see now, sorry for the confusion. The reads you provided only have MinKNOW basecalls and no event data. You'll need to re-basecall your dataset with albacore, then use `nanopolish extract -b albacore` to do the extraction.

**Comment by jordur** [comment]
Ok! That's exactly what I wanted to know. So, re-basecalled reads with albacore could be used in the following script??
```
python nanopolish_makerange.py Canu_assembly_contigs.fasta | parallel --results nanopolish.results -P 8 \ nanopolish variants --consensus=polished.{1}.fa -w {1} -r Sample_collapse.fasta -b Sample.contigs.sorted.bam -g Canu_assembly_Sample.contigs.fasta -t 8
```
i.e. extracted reads with poretools and assembled with Canu could be polished with new albacore basecalling?
Thank you very much

**Comment by jts** [comment]
Yes but I suggest you extract with nanopolish extract rather than poretools to make sure all of the groups are set up correctly in the headers. Otherwise it looks fine.

**Comment by jordur** [comment]
Done! It worked! I performed again the basecalling with albacore and nanopolish extract returned (as expected) fasta sequences.
Thanks a lot Jared, your help was definitively helpful!

**Comment by jts** [comment]
Thanks, glad to hear it.

**Comment by woodford87** [comment]
Similar problems here using Albacore basecalled fast5 files.
Mac OS X Sierra with nanopolish 0.6.1 via Docker. nanopolish appears to be installed correctly however nanopolish extract -t 2d on individual (or directories of) .fast5 files reports:
[filename]` is neither a fast5 file nor a directory`
h5dump of [filename] appears OK, though no reference to albacore (should there be?)

We've also tried to force basecalling with `nanopolish extract -b albacore` but this reports that -b is an invalid option or

```
docker run adbailey4/nanopolish extract -b albacore --type 2d [filename]
extract: invalid option -- 'b'
= extract.0 nanopolish_extract.cpp:225 process_path path [albacore] is neither a fast5 file nor a directory
```

Installing nanopolish directly from github fails with clang and eigen issues which we've not managed to fix (due to our incompetence I suspect)

With thanks

**Comment by esolares** [comment]
Hi, I am getting errors in the last step where some of the contigs from makerange fail. This then inturn does not allow nanopolish to finish as parts of contigs are missing. I try to rerun that section of the original assembly contig and get the same error:
Error: could not find path to FAST5 for read 00001256-a822-49ff-bc72-f49bc3c8b5e3
Please make sure that this path is accessible
I then did some digging noticed you recommended using nanopolish extract, but I am not able to extract anything as none of the reads are suitable for nanopolish. I did an h5dump on a fast5 file and have the following:
{
FILE_CONTENTS {
 group      /
 group      /Raw
 group      /Raw/Reads
 group      /Raw/Reads/Read_4237
 dataset    /Raw/Reads/Read_4237/Signal
 group      /UniqueGlobalKey
 group      /UniqueGlobalKey/channel_id
 group      /UniqueGlobalKey/context_tags
 group      /UniqueGlobalKey/tracking_id
 }
}
I originally extracted the sequences using albacore 1.2.1

Please let me know if I need to change something or if I am doing something wrong. Thank you.
