### ISSUE TITLE
GpC methylation training fails

### ISSUE THREAD

**Issue by cvermeulen88** [jts/nanopolish#964]
Dear developers,

I am trying to train a model for GpC methylation using nanopolish train
I am providing the tool with the following inputs:
--reads
--bam
A fastq with all reads, indexed using nanopolish index, and a .bam file with them all mapped to the lambda phage genome. This sample consists of lambda phage DNA that has been enzymatically converted, so it should contain (almost) exclusively methylated Gp5mC sites.

--genome
A genome .fasta file, where all instances of GC have been replaced with "GM" indexed with "bwa index".

-d an output directory

-i an input model, which is template model "ont_model_name r9.4_180mv_450bps_6mer", which has been expanded using tool "expand_model_alphabet.py" (https://github.com/jts/methylation-analysis/blob/master/expand_model_alphabet.py) with the CpG setting, and afterwards I changed the alphabet in the header to "gpc". perhaps this is at the root of it, but expand_model_alphabet.py doesn't seem to have a gpc option? 

When I run nanopolish train, it works for a while, but then it crashes with the following message:

...
Inferring read 4ddbf058-a09e-413e-93ae-18c448dc279d J02459.1:2673-3788 0
Inferring read 835539f2-e52a-4c27-b2b4-bfa8cc1b1880 J02459.1:2681-6038 0
Inferring read 29f6ad5d-8f2b-4446-a09c-2976cff08a16 J02459.1:2679-4280 0
Inferring read da41cb81-5ed9-4214-b232-3a259b66e25f J02459.1:2660-4736 0
nanopolish: src/common/nanopolish_alphabet.h:145: virtual std::string Alphabet::reverse_complement(const string&) const: Assertion `str[i] != 'M'' failed.
Aborted (core dumped)

I don't really understand the coding in the nanopolish_alphabet.h script so I'm having trouble figuring out where this error comes from.

With kind regards,
Carlo

**Comment by jts** [comment]
Hi,

We have a trained GpC model in the `nanonome` branch that you may want to use rather than training your own:

https://github.com/jts/nanopolish/tree/nanonome

Right now, training your own model requires writing a bit of C++ code. If you'd like to train your own GpC model, you'll need to set the structs in nanopolish_alphabet to define what GpC methylation looks like. It will be easiest to just copy all the `GpC` structs from here:

https://github.com/jts/nanopolish/blob/nanonome/src/common/nanopolish_alphabet.h#L392
